base_model: /workspace/models/Llama-3.1-8B/
merge_method: ties
models:
- model: /workspace/models/llama-3.1-8b-smol/
  parameters:
    density: 1
    weight: 0.1
- model: /workspace/models/smol-experts/llama-3.1-8b-expert-code/
  parameters:
    density: 1
    weight: 0.9
