base_model: /workspace/models/Llama-3.2-3B/
merge_method: ties
models:
- model: /workspace/models/llama-3.2-3b-smol/
  parameters:
    density: 1
    weight: 0.1
- model: /workspace/models/smol-experts/llama-3.2-3b-expert-math/
  parameters:
    density: 1
    weight: 0.9
